version: '3.4'

services:
  backendexercize:
    image: ${DOCKER_REGISTRY-}backendexercize
    build:
      context: .
      dockerfile: BackendExercize/Dockerfile
    environment:
      server: db
      port: 5432
      userId: postgres
      password: password
      database: twitter
  db:
    image: doyce/twitter-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: postgres